name: code quality actions
on: [push]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version-file: .python-version
      
      - name: Install deps
        run: make install

      - name: Lint
        run: make lint

      - name: Test
        run: make test
